// jgabaut @ github.com/jgabaut
// SPDX-License-Identifier: GPL-3.0-only
/*
    Copyright (C) 2024 jgabaut

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "canvil_py.h"

void canvil_py_subst_dashes(const char* src, char* dest) {
    for (size_t i=0; i < strlen(src); i++) {
        char c = src[i];
        if (c == '-') {
            c = '_';
        }
        dest[i] = c;
    }
    dest[strlen(src)+1] = '\0';
}

int canvil_py_handle_build(Spuro logger, const char* builds_dir_optarg, Koliseo_Temp* kls_t) {
    const char* cmd_args[2] = {
        [0] = "python -m build", // -o would avoid the need to rename later
        [1] = NULL,
    };

    Komando cmd = new_shell_command_kls_t(1, cmd_args, kls_t);
    bool run_res = run_command(cmd);
    if (run_res) return 0;
    return -1;
}

void canvil_py_extract(const char *filename, const char *output_dir, Spuro logger) {
    struct archive *a = archive_read_new();
    struct archive *ext = archive_write_disk_new();
    struct archive_entry *entry;
    int r;

    archive_read_support_format_tar(a);
    archive_read_support_filter_gzip(a);  // Handles .gz
    r = archive_read_open_filename(a, filename, 10240); // Block size
    if (r != ARCHIVE_OK) {
        spr_logf_to(logger, SPR_ERROR, "Error: %s", archive_error_string(a));
        return;
    }

    while (archive_read_next_header(a, &entry) == ARCHIVE_OK) {
        const char *orig_path = archive_entry_pathname(entry);

        // Strip the first path component
        const char *stripped = strchr(orig_path, '/');
        if (stripped == NULL || stripped[1] == '\0') {
            // Skip top-level empty directories or broken entries
            continue;
        }
        stripped++; // skip the '/'

        // Build the new output path
        char fullpath[4096];
        snprintf(fullpath, sizeof(fullpath), "%s/%s", output_dir, stripped);
        archive_entry_set_pathname(entry, fullpath);

        r = archive_write_header(ext, entry);
        if (r != ARCHIVE_OK) {
            fprintf(stderr, "Write header failed: %s\n", archive_error_string(ext));
        } else {
            const void *buff;
            size_t size;
            la_int64_t offset;

            while ((r = archive_read_data_block(a, &buff, &size, &offset)) == ARCHIVE_OK)
                archive_write_data_block(ext, buff, size, offset);

            archive_write_finish_entry(ext);
        }
    }

    archive_read_free(a);
    archive_write_free(ext);
}

int canvil_py_handle_unpack(const char* srcdist_path, const char* bindir_optarg, const char* tagname, Spuro logger) {
    char target_path[FILENAME_MAX] = {0};
    sprintf(target_path, "%s/v%s/unpack", bindir_optarg, tagname);
    spr_logf_to(logger, SPR_DEBUG, "Unpacking {%s} -> {%s}", srcdist_path, target_path);

    canvil_py_extract(srcdist_path, target_path, logger);
    return 0;
}

int canvil_py_gen_shim(const char* shim_path, const char* module_path, const char* entrypoint, Spuro logger) {
    spr_logf_to(logger, SPR_DEBUG, "Generating anvilpy shim. Target path: {%s} Module path: {%s} Function: {%s}", shim_path, module_path, entrypoint);
    FILE* fp = fopen(shim_path, "w");
    if (!fp) {
        spr_logf_to(logger, SPR_ERROR, "Failed opening shim path {%s}", shim_path);
        return -1;
    }
    char shim_string[FILENAME_MAX] = {0};
    sprintf(shim_string, "#!/bin/python3\n\n##\n# Generated by canvil v%s\n# Repo at https://github.com/jgabaut/canvil\n##\n\nimport sys\nimport re\nfrom %s.%s import %s\n\nif __name__ == \'__main__\':\n    sys.argv[0] = re.sub(r'(-script\\.pyw|\\.exe)?$', '', sys.argv[0])\n    sys.exit(%s())\n", CANVIL_API_VERSION_STRING, "unpack", module_path, entrypoint, entrypoint);
    fprintf(fp, "%s\n", shim_string);
    fclose(fp);

    // Set permissions to 744 (rwxr--r--)
    if (chmod(shim_path, 0744) != 0) {
        spr_logf_to(logger, SPR_ERROR, "Failed chmod on {%s}", shim_path);
        return -1;
    }
    return 0;
}

bool canvil_py_handle_postbuild(AnvilPy_Env anvilpy_env, const char* targetdir_optarg, const char* tagname, Spuro logger)
{
    bool res = true;
    char proj_name_dashless[FILENAME_MAX] = {0};
    canvil_py_subst_dashes(anvilpy_env.proj_name, proj_name_dashless);
    char srcdist_path[FILENAME_MAX] = {0};
    char whldist_path[FILENAME_MAX] = {0};
    sprintf(srcdist_path, "./dist/%s-%s.tar.gz", proj_name_dashless, tagname);
    sprintf(whldist_path, "./dist/%s-%s-py3-none-any.whl", proj_name_dashless, tagname);
    char srcdist_dest_path[FILENAME_MAX] = {0};
    char whldist_dest_path[FILENAME_MAX] = {0};
    sprintf(srcdist_dest_path, "%s/v%s/%s-%s.tar.gz", targetdir_optarg, tagname, proj_name_dashless, tagname);
    sprintf(whldist_dest_path, "%s/v%s/%s-%s-py3-none-any.whl", targetdir_optarg, tagname, proj_name_dashless, tagname);
    spr_logf_to(logger, SPR_DEBUG, "mv {%s} -> {%s}", srcdist_path, srcdist_dest_path);
    int rename_res = rename(srcdist_path, srcdist_dest_path);
    if (rename_res == 0) {
        spr_logf_to(logger, SPR_DEBUG, "mv {%s} -> {%s}", whldist_path, whldist_dest_path);
        rename_res = rename(whldist_path, whldist_dest_path);
    } else {
        spr_logf_to(logger, SPR_ERROR, "Failed mv {%s} -> {%s}", srcdist_path, srcdist_dest_path);
        res = false;
    }
    int unpack_res = -1;
    if (rename_res == 0) {
        spr_logf_to(logger, SPR_DEBUG, "Unpacking srcdist");
        unpack_res = canvil_py_handle_unpack(srcdist_dest_path, targetdir_optarg, tagname, logger);
    } else {
        spr_logf_to(logger, SPR_ERROR, "Failed mv {%s} -> {%s}", whldist_path, whldist_dest_path);
        res = false;
    }
    if (unpack_res == 0) {
        spr_logf_to(logger, SPR_DEBUG, "Generating shims");
        int shim_res = -1;
        for (size_t i=0; i < anvilpy_env.scripts_len; i++) {
            char shim_path[FILENAME_MAX] = {0};
            sprintf(shim_path, "%s/v%s/%s", targetdir_optarg, tagname, anvilpy_env.scripts[i]->name);
            const char *delimiter = ":";

            char *token = strtok(anvilpy_env.scripts[i]->entrypoint, delimiter);
            char module_path[FILENAME_MAX] = {0};
            char entrypoint[FILENAME_MAX] = {0};
            int k = 0;
            while (token != NULL) {
                if (k==0) {
                    sprintf(module_path, "%s", token);
                    k++;
                } else {
                    sprintf(entrypoint, "%s", token);
                }
                token = strtok(NULL, delimiter);
            }
            spr_logf_to(logger, SPR_DEBUG, "Generating shim {%s} for {%s:%s}", shim_path, module_path, entrypoint);
            shim_res = canvil_py_gen_shim(shim_path, module_path, entrypoint, logger);
            if (shim_res != 0) {
                spr_logf_to(logger, SPR_ERROR, "Failed generating shim {%s} for {%s:%s}", shim_path, module_path, entrypoint);
                res = false;
            }
        }
    } else {
        spr_logf_to(logger, SPR_ERROR, "Failed unpack {%s} -> {%s/v%s/unpack", srcdist_dest_path, targetdir_optarg, tagname);
        res = false;
    }
    return res;
}
